// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyQ1HAx82Z8-rP3YggTz8LAAlt3V_lzGE',
    appId: '1:641330480786:web:914829757ead65a454c84b',
    messagingSenderId: '641330480786',
    projectId: 'fir-flutter-662b1',
    authDomain: 'fir-flutter-662b1.firebaseapp.com',
    storageBucket: 'fir-flutter-662b1.appspot.com',
    measurementId: 'G-E347J2SJ61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmb2X7fbSV0263wM6msqv9-HcMClU4fd8',
    appId: '1:641330480786:android:65bad0fd4ec96fea54c84b',
    messagingSenderId: '641330480786',
    projectId: 'fir-flutter-662b1',
    storageBucket: 'fir-flutter-662b1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyQ1HAx82Z8-rP3YggTz8LAAlt3V_lzGE',
    appId: '1:641330480786:web:cfcbb60de3fce1ab54c84b',
    messagingSenderId: '641330480786',
    projectId: 'fir-flutter-662b1',
    authDomain: 'fir-flutter-662b1.firebaseapp.com',
    storageBucket: 'fir-flutter-662b1.appspot.com',
    measurementId: 'G-HCK7FBRVVZ',
  );
}
